#!/bin/bash

if [ "${USE_RANDOM_ALT}" = "yes" ]; then
  ALTPICNUM=$(find $(dirname "${picfnam}") -name $(basename "${picfnam%.*}_alt")* | wc -l)
  if [ "${ALTPICNUM}" -gt "0" ]; then                                     # If more than 0 _altX pictures
    ALTPICRND=$(( ${RANDOM} % $((ALTPICNUM+1)) ))                         # then dice between 0 and count of found _altX pictures
    [ "${ALTPICRND}" -gt 0 ] && picfnam="${picturefolder}/${picfolder^^}/${newcore}_alt"${ALTPICRND}".${picfolder:0:3}"
  fi                                                                      # If 0 then original picture, otherwise _altX
fi
