#!/bin/bash

#
#

! [ "$(dos2unix -ic /media/fat/tty2tft/*.ini)" = "" ] && dos2unix -k -q /media/fat/tty2tft/*.ini
. /media/fat/tty2tft/tty2tft-system.ini
. /media/fat/tty2tft/tty2tft-user.ini
cd /tmp

# Start
start() {
    ### Wait for USB module and start tty2tft daemon
    WAITEND=$((SECONDS+10))
    while !  [ -c ${TTYDEV} ] && [ ${SECONDS} -lt ${WAITEND} ]; do
      sleep 0.1
    done
    if ! [ -c ${TTYDEV} ]; then
      echo "Could not find the needed USB module ${TTYDEV}. Exiting."
      exit 1
    fi

    if [[ -x ${DAEMONSCRIPT} ]]; then
      if [ -e /run/tty2tft-daemon.pid ] && [ -d /proc/$(</run/tty2tft-daemon.pid) ]; then
	echo "${DAEMONNAME} already running"
	exit 1
      else
	echo "Starting ${DAEMONNAME}..."
	${DAEMONSCRIPT} & echo $! > /run/tty2tft-daemon.pid
      fi
    else
      echo "${DAEMONSCRIPT} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping ${DAEMONNAME}..."
    if [ -e /run/tty2tft-daemon.pid ]; then
      PIDDAEMON=$(</run/tty2tft-daemon.pid)
      PIDINOTIFY=$(ps -eo pid,ppid,args | grep $(ps | grep tty2tft | awk 'NR==1{print $1}') | tail -1 | awk '{print $1}')
      #[ -e /run/tty2tft-daemon.pid ] && PIDDAEMON=$(</run/tty2tft-daemon.pid)
      #[ -e /run/tty2tft-inotify.pid ] && PIDINOTIFY=$(</run/tty2tft-inotify.pid)
      [ ${PIDDAEMON} ] && kill ${PIDDAEMON}
      [ ${PIDINOTIFY} ] && kill ${PIDINOTIFY}
      rm -f /run/tty2tft-daemon.pid
      #rm -f /run/tty2tft-daemon.pid /run/tty2tft-inotify.pid
    fi
}

case "$1" in
  start)
        start
        ;;
  stop) 
        stop
        ;;
  restart)
        stop
        start
        ;;
#  reload)
#       reload
#       ;;
  *)
#        echo "Usage: $0 {start|stop|restart|reload}"
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
